name: Deploy Vite SPA

on:
    push:
        branches: [main]
        paths:
            - "movieapi/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
            run:
                shell: bash
                working-directory: ./movieapi
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        # Frontend build
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
             node-version: '18' 

        - name: Install dependencies
          run: |
            npm i  # Uses package-lock.json for exact versions
          
        - name: Build Vite project
          run: npm run build
            # This will create the dist directory with the built files

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        # Deploy to S3
        - name: Upload to S3
          run: |
            # Get the bucket name from Terraform output
            aws s3 sync dist/ s3://movieapi-223769697

        # Invalidate CloudFront
        - name: Invalidate CloudFront
          run: |
            # Get the distribution ID from Terraform output
            DISTRIBUTION_ID=$(terraform output -raw cloudfront_distribution_id)
            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"