name: Deploy Vite SPA

on:
    push:
        branches: [main]
        paths:
            - "movieapi/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Frontend build
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm i  # Uses package-lock.json for exact versions
          
      - name: Build Vite project
        run: npm run build
        # This will create the dist directory with the built files

      # Infrastructure deployment
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Deploy to S3
      - name: Upload to S3
        run: |
          # Get the bucket name from Terraform output
          BUCKET_NAME=$(terraform output -raw website_bucket_name)
          aws s3 sync dist/ s3://$BUCKET_NAME

      # Invalidate CloudFront
      - name: Invalidate CloudFront
        run: |
          # Get the distribution ID from Terraform output
          DISTRIBUTION_ID=$(terraform output -raw cloudfront_distribution_id)
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"